name: country_picker_plus
description: A flutter package to display list of Countries, States and Cities depends on Selected, also you can search country, state, and city all around the world.
version: 2.0.2
homepage: https://github.com/real-ali/country_picker_plus

environment:
  sdk: '>=2.19.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
 
 
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/countries.json